---
- hosts: nginx
  tasks:
    - name: Update config
      copy: src=files/nginx/nginx.conf dest=/etc/nginx/nginx.conf mode=0644
      register: nginx_config
      ignore_errors: True

    - name: reload nginx
      service: name=nginx state=reloaded
      when: nginx_config|success
